# NumPy Array Reshaping

**Reshaping** in NumPy means changing the shape of an array **without changing its data**.

---

## What is Reshaping?

Reshaping modifies how elements are arranged across dimensions while keeping the **total number of elements constant**.

> Total elements before reshape = Total elements after reshape

---

## `reshape()` Function

```python
array.reshape(new_shape)

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])  #1d array


In [6]:
# 1d to 2d array
newarr = arr.reshape(3, 4)

In [4]:
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#1d to 3d array

newdata1 = arr.reshape(2,3,2)

In [8]:
print(newdata1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Array Indexing

### Array imdex is same as assiging an array element.

In [12]:
arr = np.array([1,2,3,4,])  #accesing 1d array
print(arr)

[1 2 3 4]


In [13]:
print(arr[2] + arr[3])  #adding the sum of 2 index by menstioning the index number

7


In [18]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # indexing for 2d array
print(arr[0,1])  # 1st row and 2nd element means 2
print(arr[1,4])  # this indicates 2nd row and 5th element it is 10

2
10


In [20]:
arr =  np.array([[[1,2,3],[4,5,6,],[8,9,0]]])
print(arr[1,1,0])

IndexError: index 1 is out of bounds for axis 0 with size 1