## Array (List) Slicing in Python

### Syntax
```python
array[start:end:step]
arr[start : end]
	•start → where to begin (included)
	•end → where to stop (not included)

arr = [10, 20, 30, 40, 50, 60]
index=  0   1   2   3   4   5

Part---->Meaning (simple words)
start-->where you start walking
end---->where you stop BEFORE
step--->how many steps you jump


In [31]:
arr = np.array([10, 20, 30, 40, 50, 60])  # 1d array 

In [32]:
import numpy as np  # import numpy library

In [33]:
arr1 = arr[2:4]  # slicing of array

In [34]:
print(arr1) # print arr1

[30 40]


In [35]:
a2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [36]:
# a2[1, 1:4]
# a2[0:2, 2]
a2[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

## 2D ARRAY

### Rule for 2D slicing (NumPy style)
    array[rows , columns]

In [41]:
# 2D array = table (rows & columns)
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [42]:
arr2d[0]     # to get first row

array([1, 2, 3])

In [43]:
arr2d[:, 1]

array([2, 5, 8])

## 3d array

	•3 blocks (layers)
	•each block has 3 rows
	•each row has 3 columns

-**Block 0 → numbers 10–18**

-**Block 1 → numbers 20–28**

-**Block 2 → numbers 30–38**

|    | C0 | C1 | C2 |
|----|----|----|----|
| R0 | 1  | 2  | 3  |
| R1 | 4  | 5  | 6  |
| R2 | 7  | 8  | 9  |

## Golden rule for 3D slicing 

- `array[ block , row , column ]`

In [45]:
a3 = np.array([
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
    [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

In [46]:
a3.shape  #matrix

(3, 3, 3)

In [49]:
a3[:, :, 0] # all blocks : all rows : column o only

array([[10, 13, 16],
       [20, 23, 26],
       [30, 33, 36]])

In [50]:
# All blocks, row 1, all columns

a3[:,1,:]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [51]:
# First two blocks only
a3[0:2,:,:]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [52]:
# Skip blocks (step usage)

a3[::2, :, :]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [53]:
# Understanding start:end:step in 3D (simple words)

a3[0:3:2,:,1]

array([[11, 14, 17],
       [31, 34, 37]])

### (VERY IMPORTANT)
-`1D → array[index]`

-`2D → array[row, column]`

-`3D → array[block, row, column]`

-`:` always means take everything

-`step means jump`