## `View` and `Copy` array

- copy is new array and view is just to view the original array

- if we make any changes in the copy it wont effext to the original array
- where as in the view array it will change in the original array also 

In [3]:
import numpy as np

In [18]:
arr = np.array([1,2,3,4,5,6])

In [19]:
# copy menthod

copy = arr.copy()
copy[0] = 2002
print(copy)
print(arr)       # whare as in copy it original wont change and it create a copy of the result seperately

[2002    2    3    4    5    6]
[1 2 3 4 5 6]


In [20]:
# view method

view = arr.view()
view[2] = 3112
print(view)
print(arr)           # in viwe original data will also change

[   1    2 3112    4    5    6]
[   1    2 3112    4    5    6]


# Numpy-major-minor-opperation

## `Append` Operation in NumPy
- Adds new rows or columns to an existing 2D array.
- Uses np.append() (must specify axis).
____________________
 ```python
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.append(a, [[5, 6]], axis=0)

print(b)

In [37]:
a = np.array([[1,2,3],
             [4,5,6]])  # 2d array

# You didn’t say where → NumPy put it at the end
# You cannot choose the position

np.append(a, [[7,8,9]], axis = 0)  # this is for row 
np.append(a, [[7],[8]], axis = 1)    # this is for column

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

# `Insert` Operation in NumPy
- Inserts elements at a specific position.
- `Uses np.insert().`

🔹 **np.insert()**
- Used to add new values into an array.

🔹 **a**
- The original array where we want to insert data.

🔹**1**
- The position (index) where the new row will be added.
- Index 1 means → second row position
(Index counting starts from 0)

🔹 **[[9, 10, 11]]**
- This is the new row we are inserting.
- It has 3 values because the array has 3 columns.

🔹 **axis = 0**
- axis=0 means row operation.
- So NumPy knows we are inserting a row, not a column.
__________________
```python
d = np.insert(a, 1, [[9, 10]], axis=0)

print(d)

In [41]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

d = np.insert(a, 1, [[9, 10, 11]], axis=0) # insert means “add at this exact place”
print(d)

[[ 1  2  3]
 [ 9 10 11]
 [ 4  5  6]]


## `Delete` operation in python

- Delete means remove a row or a column from an array.
- Uses np.delete()
- Original array does not change (a new array is created).

### Golden Rule

- axis = 0 → Delete row
- axis = 1 → Delete column
________________________
```python
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.delete(a, 1, axis=0)
print(b)

In [44]:
a = np.array([[12,13,14],
             [15,16,17]])

b = np.delete(a,1, axis=0)  # delete rown [15,16,17]
print(b)

[[12 13 14]]


# NumPy `Concatenation` 

- Concatenation means joining arrays together.
- You can join arrays row-wise or column-wise.
- `Uses np.concatenate().`

- **Shape rule** (VERY important)
- `axis = 0` → columns must match
- `axis = 1` → rows must match

# Easy memory trick

- `Concatenate = join arrays`
- `Append = add at end`
- `Insert = add at position`
___________________________

```python
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

c = np.concatenate((a, b), axis=0)
print(c)

In [49]:
a = np.array([[5,6],
              [7,8]])

b = np.array([[1,2],
              [3,4]])

c = np.concatenate((b,a), axis=0)  # where concatente meanst to join two array
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
d = np.concatenate((a, b), axis=1)
print(d)

[[5 6 1 2]
 [7 8 3 4]]


# `hstack` and `vstack` in NumPy

- `hstack` → join arrays side by side (columns)
- `vstack` → join arrays one below another (rows)
_____________


In [51]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [52]:
# vstak

c = np.vstack((a,b))   # rows
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [53]:
# hstack

d = np.hstack((a,b))  # colomns
print(d)

[[1 2 5 6]
 [3 4 7 8]]
